'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ogrenciler
    
    '''<summary>
    '''txtOgrno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOgrno As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAdsoyad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdsoyad As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtbolum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbolum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fuResim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuResim As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''btnKaydet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnKaydet As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lbSonuc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSonuc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvResimler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvResimler As Global.System.Web.UI.WebControls.GridView
End Class
